// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// const dbUrl =
//   "postgresql://postgres.hxrhkndhpqrusdtxranj:Mahsez.3692@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true";
// // const dbUrl = process.env.DATABASE_URL;

// if (!dbUrl) {
//   throw new Error("DATABASE_URL missing");
// }

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url: dbUrl,
    url: "postgresql://postgres.hxrhkndhpqrusdtxranj:Mahsez.3692@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
  },
});
